AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  cfnAnnex:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      # Read-only access required for the test_template.yml
      Policies: 
        - AWSCloudFormationReadOnlyAccess
        - AmazonEC2ReadOnlyAccess
      Runtime: nodejs4.3
      CodeUri: lambda_function/
      Timeout: 300
Outputs:
  cfnAnnexARN:
    Description: ARN of the cfn-annex function
    Value: !GetAtt cfnAnnex.Arn
    Export:
      Name: cfn-annex
